Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Clinic_Management_System.Models;
using System.Diagnostics;

namespace Clinic_Management_System.Controllers
{
    public class PatientsController : Controller
    {
        private ClinicDBEntities db = new ClinicDBEntities();

        // GET: Patients
        public async Task<ActionResult> Index()
        {
            Debug.WriteLine(User);
            return View(await db.patients.ToListAsync());
        }

        // GET: Patients/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = await db.patients.FindAsync(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        public async Task<ActionResult> AddMedicine(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = await db.patients.FindAsync(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMedicine([Bind(Include = "patient_id,patient_name,patient_age,patient_visit_date,patient_symptoms,patient_medicine")] patient pat)
        {
            if (ModelState.IsValid)
            {
                using(var context = new ClinicDBEntities())
                {
                    patient p = context.patients.Single(x => x.patient_id == pat.patient_id);
                    p.patient_medicine = pat.patient_medicine;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
              
               
            }

            return View(pat);
        }

        // GET: Patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "patient_id,patient_name,patient_age,patient_visit_date,patient_symptoms,patient_medicine")] patient patient)
        {
           
            if (ModelState.IsValid)
            {
                db.patients.Add(patient);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: Patients/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = await db.patients.FindAsync(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "patient_id,patient_name,patient_age,patient_visit_date,patient_symptoms,patient_medicine")] patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = await db.patients.FindAsync(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            patient patient = await db.patients.FindAsync(id);
            db.patients.Remove(patient);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Clinic Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand  text-black text-capitalize text-bold" })
            </div>
            <div class="navbar-collapse" style="display:flex">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("See Patients", "Index", "Patients")</li>
                    }
                </ul>
                <ul class="nav navbar-nav flex-grow-1" style="margin-left:auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li> <a class="text-primary font-weight-normal">Welcome, @User.Identity.Name</a> </li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                    else
                    {

                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                        <li>@Html.ActionLink("Register", "Signup", "Account")</li>

                    }
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    <footer>
        <p class="mb-0 text-center">&copy; @DateTime.Now.Year - Clinic Management Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>